Add aria-labels to make UI more accessible
FreeFeed/freefeed-react-client pull request #1270
Opened 2021-01-28 09:59 UTC by n1313

Я немного поигрался с VoiceOver (как описано http://css.yoksel.ru/inaccessibility/) на главном фронтенде и пришел к выводу, что фрифидом сложно пользоваться, опираясь только на слух. Многие элементы интерфейса не названы совсем (контролы клайков), некоторые из-за особенностей верстки названы некорректно (заголовки фидов), некоторые подписаны кое-как (автор комментария звучит как просто последнее слово в тексте комментария), и практически нет возможности быстро переходить от неинтересного контента (например, ранее прослушанного поста) в поисках чего-нибудь новенького.

Для работы над этим пулл-реквестом я начал добавлять текстовые лейблы там, где их, по-моему, не хватает, проверяя результаты в Accessibility Inspector в Фаерфоксе и в VoiceOver. Я не специалист, но, по-моему, получилось неплохо. Теперь VoiceOver объявляет информацию о каждом посте без захода в пост, регионы внутри поста названы (что позволяет их пропускать), и некоторые ранее неподписанные кнопки и ссылки теперь подписаны, что позволяет ими бесстрашно пользоваться.

2021-01-28 14:49 UTC, davidmz commented on src/components/post.jsx
> +    } comments and ${props.likes.length} likes`;
У нас есть функция pluralForm в src/utils/index.js, её можно тут использовать. И, может быть, не писать '0 likes/comments', когда их ноль?

2021-01-28 14:50 UTC, davidmz approved these changes
Это очень-очень-очень круто!)

2021-01-28 14:55 UTC, n1313 commented on src/components/post.jsx
> +    } comments and ${props.likes.length} likes`;
Я думал пропускать ноль, но решил указать явно. По-моему, различить состояния "информация про лайки-комменты не дана, потому что она не дана для всех постов" и "информация про лайки-комменты не дана, потому что у конкретного поста их нет" сложнее, если опираешься только на слух.

2021-01-28 15:23 UTC, indeyets requested changes
Поддерживаю запрос на plural! поправь пожалуйста.
И, да, спасибо огромное! выглядит замечательно!

2021-01-30 06:06 UTC, n1313 commented
Поправил plural.

2021-01-30 13:21 UTC, n1313 commented
Любопытно, что инстаграм, твиттер и реддит так не делают (не кладут описания постов в лейблы контейнерам постов), а фейсбук делает (через aria-labelledby, но это мелочь). Придумал эту фичу без подглядывания в фейсбук и горд собой.

2021-02-01 09:30 UTC, merged