Add rel="noopener" 🕶 to all possibly external links
FreeFeed/freefeed-react-client pull request #1334
Opened 2021-03-12 09:19 UTC by davidmz

It improves both security and performance. See https://web.dev/external-anchors-use-rel-noopener/

Also the `meta name='referrer' content='strict-origin-when-cross-origin'` tag added to the index.

2021-03-15 03:35 UTC, n1313 requested changes

2021-03-15 03:35 UTC, n1313 commented on CHANGELOG.md
> +### Changed
Доктор, у меня в глазах двоится

2021-03-15 03:35 UTC, n1313 commented on src/components/libera-pay-widget.jsx
> +      rel="noopener noopener"
И вот опять

2021-03-15 03:37 UTC, n1313 commented
Может, сделать компонент для внешних ссылок? Если в будущем еще что-нибудь придумаем для них (например, редиректить через какую-нибудь прощальную страничку, или выделять их спец-стилями), то не надо будет по всей базе бегать

2021-03-15 07:47 UTC, davidmz commented
Я тут немного поисследовал, и понял, что, наверное, перестраховался. Сейчас почти все браузеры подразумевают noopener для ссылок с target=_blank:
* [Firefox 79](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/79) 06.2020
* [Safari TP 68](https://webkit.org/blog/8475/release-notes-for-safari-technology-preview-68/) 10.2018
* [Chrome 88](https://developer.chrome.com/blog/new-in-chrome-88/) 01.2021

Поэтому, наверное, можно его явно не писать. Но я бы предложил добавить eslint-правило, которое требует target=_blank для &lt;a> c href. Локальные ссылки у нас всё равно делаются через Link.

2021-07-06 18:08 UTC, n1313 commented
Тем не менее, у eslint есть правило, которое ругается на это (его у нас нет, по-моему, но наличие правила подразумевает наличие проблемы). В принципе, мне кажется, что улучшение микроскопическое и, возможно, не стоит того, но, думаю, этот пиар надо либо дотащить и вмержить, либо закрыть. Меня незакрытые драфты нервируют :)

2021-07-06 18:14 UTC, closed without merging