Add tests for post editing
FreeFeed/freefeed-react-client pull request #1357
Opened 2021-04-12 15:33 UTC by n1313

This PR adds a little bit more tests for post.jsx.

2021-04-14 15:46 UTC, davidmz requested changes
На моей машине тесты не проходят с таким вот сообщением. Где-то как-то нужно зафиксировать часовой пояс.

![image](https://user-images.githubusercontent.com/132120/114739486-9739ee00-9d51-11eb-919c-fed2ff05e2ec.png)

2021-04-20 13:03 UTC, n1313 commented
@davidmz это очень странно, потому что часовой пояс зафиксирован через `cross-env TZ=utc`, как ты мне сказал сделать в прошлом пулл-реквесте, работает как надо на билд-сервере, и работает как надо на моей машине во всех часовых поясах. Как ты запускаешь тесты?

2021-04-20 13:07 UTC, davidmz commented
Я запускаю yarn test и прямо сейчас на stable вижу это:

![image](https://user-images.githubusercontent.com/132120/115400866-6dba1000-a1f2-11eb-99e3-fb9fc82d5c38.png)

2021-04-20 13:24 UTC, n1313 commented
Воспроизвелось на винде :(

2021-04-20 13:28 UTC, davidmz commented
Кажется, это особенность Windows, есть даже утилитка https://www.npmjs.com/package/set-tz, которая делает так: https://github.com/capaj/set-tz/blob/master/index.js

Надо выяснить, можно ли тут сделать что-то менее деструктивным образом…

2021-04-20 13:28 UTC, davidmz commented
https://github.com/nodejs/node/issues/4230

2021-04-20 13:36 UTC, davidmz commented
К данному PR это, получается, отношения не имеет

2021-04-20 13:40 UTC, n1313 commented
Это получается проблема с тестированием компонента TimeDisplay. Мы его раньше не тестировали, поэтому о проблеме не имели понятия. Давай я в отдельном пулл-реквесте попробую повозиться? Я думаю, там можно будет через dateFns что-нибудь подкрутить. Переменная окружения TZ передается, надо будет, наверно, руками ее учитывать в расчетах времени

2021-04-20 13:41 UTC, davidmz commented
Да, согласен. Все даты через него выводятся, так что достаточно будет пофиксить там.

2021-04-20 14:00 UTC, davidmz approved these changes

2021-04-20 14:00 UTC, merged