Allow users to leave the direct message (except the author of the message)
FreeFeed/freefeed-react-client pull request #1484
Opened 2021-12-13 12:32 UTC by davidmz

2021-12-13 19:09 UTC, n1313 requested changes

2021-12-13 19:09 UTC, n1313 commented on src/components/post-more-menu.jsx
> +      confirm('Are you sure you want to leave this conversation and loose access to this post?') &&
`loose` =>`lose`. Немного странно, что мы называем один и тот же предмет (директ) двумя разными словами (conversation и post). Может, что-то типа `Are you sure you want to leave this conversation? You won't be able to read it unless the author invites your back again.`?

2021-12-13 21:10 UTC, davidmz commented on src/components/post-more-menu.jsx
> +      confirm('Are you sure you want to leave this conversation and loose access to this post?') &&
По-моему, просто “invites you back” уточнение лишнее.

2021-12-13 21:16 UTC, n1313 commented on src/components/post-more-menu.jsx
> +      confirm('Are you sure you want to leave this conversation and loose access to this post?') &&
Не очень понял тебя. Какую именно формулировку ты предлагаешь?

Лично я бы предпочел один из двух вариантов:

1. `Are you sure you want to leave this conversation?`
2. `Are you sure you want to leave this conversation? You won't be able to read it unless the author invites your back again.`

2021-12-13 21:19 UTC, davidmz commented on src/components/post-more-menu.jsx
> +      confirm('Are you sure you want to leave this conversation and loose access to this post?') &&
Ну можно первую. Просто вероятность приглашения назад мне кажется довольно низкой.

Conversation мне тоже не особо нравится, но leave this post выглядит страннее.

2021-12-13 21:21 UTC, n1313 commented on src/components/post-more-menu.jsx
> +      confirm('Are you sure you want to leave this conversation and loose access to this post?') &&
Это не про вероятности. Откуда нам знать, что происходит в этом директе между этими людьми, и какая вероятность того, что они чего-то сделают или нет? Суть этого сообщения в том, что покидание директа -- не необратимая операция, и мне кажется важным об этом юзеру сказать. Можно покинуть директ, а можно в него обратно попасть. Пусть делают дальше с этим, что хотят

2021-12-14 06:37 UTC, davidmz commented on src/components/post-more-menu.jsx
> +      confirm('Are you sure you want to leave this conversation and loose access to this post?') &&
Ну ок, пусть так быдет

2021-12-14 06:37 UTC, n1313 approved these changes, later dismissed

2021-12-22 17:15 UTC, n1313 approved these changes

2021-12-22 17:15 UTC, merged