Fix crash when selector is not valid
FreeFeed/freefeed-react-client pull request #1522
Opened 2022-03-27 20:44 UTC by n1313

Fixes UI crash that happens if URL anchor is an invalid querySelector (e.g. https://freefeed.net/settings/appearance#beta=). 

<img width="616" alt="Screenshot 2022-03-26 at 15 34 04" src="https://user-images.githubusercontent.com/632081/160300168-a5f3c2ea-fe46-4350-818d-e7568289a0c6.png">

2022-03-28 06:47 UTC, davidmz requested changes
Я согласен, что тут надо иметь более устойчивый к ошибкам код. Но кажется, я с самого начала его неправильно готовил:) Нас же тут интересует только ID элемента, поэтому querySelector, в общем, не нужен, достаточно getElementById(anchor). И тогда try/catch не понадобится.

2022-03-28 07:43 UTC, n1313 commented
Справедливо, исправлю 

Sent from my iPhone

> On Mar 27, 2022, at 23:47, David Mzareulyan ***@***.***> wrote:
> 
> ﻿
> @davidmz requested changes on this pull request.
> 
> Я согласен, что тут надо иметь более устойчивый к ошибкам код. Но кажется, я с самого начала его неправильно готовил:) Нас же тут интересует только ID элемента, поэтому querySelector, в общем, не нужен, достаточно getElementById(anchor). И тогда try/catch не понадобится.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

2022-04-03 08:26 UTC, davidmz commented on src/components/settings/forms/appearance.jsx
> +    const element = document.getElementById(`#${anchor}`);
Только тут не нужно '#' :)

2022-04-03 18:13 UTC, n1313 commented
:(

Sent from my iPhone

> On Apr 3, 2022, at 01:26, David Mzareulyan ***@***.***> wrote:
> 
> ﻿
> @davidmz commented on this pull request.
> 
> In src/components/settings/forms/appearance.jsx:
> 
> > @@ -49,8 +49,9 @@ export default function AppearanceForm() {
>      if (!hash) {
>        return;
>      }
> -    const anchor = hash.slice(1);
> -    const element = document.querySelector(`#${anchor}`);
> +    const anchor = encodeURIComponent(hash.slice(1));
> +    // eslint-disable-next-line unicorn/prefer-query-selector
> +    const element = document.getElementById(`#${anchor}`);
> Только тут не нужно '#' :)
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

2022-04-04 08:06 UTC, davidmz commented
Сорри, что так долго на таком мелком куске кода топчемся. Но я там пушнул небольшое исправление.

2022-04-04 15:31 UTC, n1313 commented
А почему decode? Я использовал encode для того, чтобы никто никаких кавычек и прочих XSS-принадлежностей не засунул в селектор.

2022-04-04 15:55 UTC, davidmz commented
В селекторе это ещё как-то понятно, но в getElementById XSS никак не возможен.

decode — потому что _теоретически_ у нас могут быть разделы с ID из странных символов, и в этом случае в хэше урла такой ID будет, видимо, url-кодированным, и поэтому его надо раскодировать. Но сейчас ничего такого нет, конечно.

2022-04-04 15:59 UTC, n1313 commented
Ну, в общем, меня всё устраивает, ждём твоего ревью :)

2022-04-04 16:00 UTC, davidmz approved these changes
Подумал, и решил одобрить

2022-04-04 16:00 UTC, merged