Fix private no refresh
FreeFeed/freefeed-react-client pull request #1551
Opened 2022-11-07 18:08 UTC by max-ermilov

Fix: private user feed is invisible after subscription approval without browser refresh

https://user-images.githubusercontent.com/93122869/200383170-ceba579a-0ac9-43ea-a5ba-31642f6c3223.mov

2022-11-08 06:28 UTC, davidmz commented
По-моему, отлично. Но ты не мог бы эти три коммита слить в один (и с понятным commit message)?

2022-11-08 11:47 UTC, max-ermilov commented
Кажется, слил.

2022-11-08 11:56 UTC, davidmz approved these changes, later dismissed
👍

2022-11-16 13:47 UTC, max-ermilov commented
Итого отображать без перезарузки клиента:
- Фид на странице приватных пользователей и групп, при подтверждении с их стороны,
- Кнопки подтверждения подписки на приватных пользователя и группы

2022-11-16 15:07 UTC, davidmz commented on src/redux/reducers.js
> +            if (!(group.id in state.subscriptions)) {
А почему тут "in" если subscription это массив?

2022-11-16 15:08 UTC, davidmz commented on src/redux/reducers.js
> +                subscriptionRequests: _.without(state.subscriptionRequests || [], user.id),
Если мы здесь, то state.subscriptionRequests точно определён, || [] не нужен.

2022-11-18 10:24 UTC, max-ermilov commented
Поправил замечания

2022-11-19 08:57 UTC, davidmz approved these changes

2022-11-23 05:23 UTC, davidmz requested changes
Напиши, пожалуйста, коротко в CHANGELOG.md, что изменилось для пользователя.

2022-11-24 05:15 UTC, davidmz approved these changes

2022-11-25 07:21 UTC, merged