Add ability to read other people's minds
FreeFeed/freefeed-react-client pull request #1674
Opened 2024-03-24 21:10 UTC by n1313

![Mar-24-2024 13-58-10](https://github.com/FreeFeed/freefeed-react-client/assets/632081/5962a60c-af2c-490c-b405-e6cab45dadef)

This is a prototype and it probably needs a bit more work.

1. to see it in action, set your local date to 2024-04-01 or change `orbitDate` in config to today
2. there are no tests because the change is date-dependent (and I'm too lazy to write date-dependent tests). Tests will fail on 2024-04-01 :(

2024-03-25 07:56 UTC, davidmz requested changes
Фича — 🔥🔥🔥 
Но есть одна небольшая проблема, напишу к конкретному месту в коде.

2024-03-25 07:59 UTC, davidmz commented on src/components/orbit.jsx
> +      {childrenRef.current ? (
Вот тут, и ещё в строке 24 childrenRef.current используется прямо в рендере. Но при первом рендере он ещё не определён, он становится ненулевым только после него. В результате, при первом рендере иконки не летают, а начинают летать только когда компонент по какой-то причине перерендеривается. Это может случаться очень нескоро.

Поскольку это нужно только для чтения размера, то можно либьо размер передавать в props (он всегда известен для юзерпика), либо читать его через useEffect, и перерендеривать Orbit сразу.

2024-03-27 07:24 UTC, davidmz commented
Отправил пару изменений, посмотри?

2024-03-28 06:03 UTC, n1313 commented
По-моему, прекрасно. Спасибо!

2024-03-28 07:42 UTC, davidmz approved these changes

2024-03-28 07:42 UTC, merged