Show a message if the viewer was blocked by the user
FreeFeed/freefeed-react-client pull request #519
Opened 2016-11-02 05:57 UTC by davidmz

When the user A (blocked by the user B) browses the page of user B, show  the message: "Nothing to show here. Perhaps %screenName% has blocked you."

2016-11-02 07:57 UTC, indeyets requested changes

2016-11-02 07:57 UTC, indeyets commented on src/components/user-feed.jsx
> +export default props => {
Add a component name, while you're changing the code. `const UserFeed = (props) => …`

2016-11-02 07:57 UTC, indeyets commented on src/components/user-feed.jsx
> +  const amIBlocked = viewUser.isPrivate === '0' && viewUser.statistics.posts !== '0' && props.visibleEntries.length === 0 && (!('offset' in query) || query.offset === '0');
shouldn't first part of condition be `!isPrivate` instead?

2016-11-02 07:57 UTC, indeyets commented on src/components/user-feed.jsx
> +  const {viewUser, location: {query}} = props;
you can move destructuring right into component-function declaration: `({ viewUser, location: { query } }) => …`

2016-11-02 07:57 UTC, indeyets commented on src/components/user-feed.jsx
> +          <p><a onClick={()=>props.userActions.unban({username: viewUser.username, id: viewUser.id})}>Un-block</a></p>
inline declaration of handlers is a bad pattern. No need to fix this here, but we should figure out something in the future

see https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md

2016-11-02 08:02 UTC, davidmz commented on src/components/user-feed.jsx
> +  const amIBlocked = viewUser.isPrivate === '0' && viewUser.statistics.posts !== '0' && props.visibleEntries.length === 0 && (!('offset' in query) || query.offset === '0');
isPrivate is a string, '0' or '1'. So I think it is better to explicitly compare it with string.

2016-11-06 09:58 UTC, indeyets approved these changes

2016-11-06 09:59 UTC, merged